kind: Service
apiVersion: v1
metadata:
  name: bus-pub
  namespace: cicd
  creationTimestamp: '2023-11-13T06:03:33Z'
  labels:
    app-name: selenium
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-11-13T06:03:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app-name': {}
        'f:spec':
          'f:clusterIPs': {}
          'f:sessionAffinity': {}
          'f:clusterIP': {}
          'f:type': {}
          'f:ipFamilyPolicy': {}
          'f:selector': {}
          'f:ipFamilies': {}
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":4442,"protocol":"TCP"}':
              .: {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":4443,"protocol":"TCP"}':
              .: {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
spec:
  clusterIP: 192.168.245.231
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 4442
      targetPort: 4442
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 192.168.245.231
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: hub
status:
  loadBalancer: {}
