kind: Service
apiVersion: v1
metadata:
  name: chromenode
  namespace: cicd
  creationTimestamp: '2023-11-13T06:02:33Z'
  labels:
    io.kompose.service: chromenode
  annotations:
    kompose.cmd: kompose up --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-11-13T06:05:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kompose.cmd': {}
            'f:kompose.version': {}
          'f:labels':
            .: {}
            'f:io.kompose.service': {}
        'f:spec':
          'f:clusterIPs': {}
          'f:sessionAffinity': {}
          'f:clusterIP': {}
          'f:type': {}
          'f:ipFamilyPolicy': {}
          'f:selector': {}
          'f:ipFamilies': {}
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":4578,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
spec:
  clusterIP: 192.168.222.224
  ipFamilies:
    - IPv4
  ports:
    - name: '4578'
      protocol: TCP
      port: 4578
      targetPort: 4578
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 192.168.222.224
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    io.kompose.service: chromenode
status:
  loadBalancer: {}
