kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: '2023-11-13T04:02:42Z'
  name: hub
  creationTimestamp: '2023-11-13T04:02:41Z'
  generation: 1
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: image.openshift.io/v1
      time: '2023-11-13T04:02:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/image.dockerRepositoryCheck': {}
          'f:labels':
            .: {}
            'f:io.kompose.service': {}
        'f:spec':
          'f:tags':
            .: {}
            'k:{"name":"4.14.1"}':
              .: {}
              'f:annotations': {}
              'f:from': {}
              'f:generation': {}
              'f:importPolicy':
                .: {}
                'f:importMode': {}
              'f:name': {}
              'f:referencePolicy':
                .: {}
                'f:type': {}
        'f:status':
          'f:dockerImageRepository': {}
  namespace: cicd
  labels:
    io.kompose.service: hub
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: selenium/hub
      generation: 1
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source