kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider=openshift
    kompose.version: 1.19.0 (f63a961c)
  name: hub
  creationTimestamp: '2023-11-13T04:03:15Z'
  generation: 9
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-11-13T08:08:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kompose.cmd': {}
            'f:kompose.version': {}
          'f:labels':
            .: {}
            'f:io.kompose.service': {}
        'f:spec':
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            .: {}
            'f:io.kompose.service': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:io.kompose.service': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"hub"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:env':
                    'k:{"name":"GRID_CLEAN_UP_CYCLE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"POOL_MAX"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_MAX_SESSION"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"JAVA_OPTS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_BROWSER_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"VNC_NO_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SE_NODE_SESSION_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":4444,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:imagePullSecrets':
                .: {}
                'k:{"name":"dockerhub"}': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
          'f:triggers': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-11-13T08:08:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:updatedReplicas': {}
          'f:readyReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:replicas': {}
          'f:availableReplicas': {}
          'f:observedGeneration': {}
          'f:unavailableReplicas': {}
          'f:latestVersion': {}
      subresource: status
  namespace: cicd
  labels:
    io.kompose.service: hub
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 1500
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 1800
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    io.kompose.service: hub
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hub
    spec:
      containers:
        - name: hub
          image: 'selenium/hub:latest'
          ports:
            - containerPort: 4444
              protocol: TCP
          env:
            - name: GRID_MAX_SESSION
              value: '1000'
            - name: GRID_BROWSER_TIMEOUT
              value: '600'
            - name: GRID_CLEAN_UP_CYCLE
              value: '300'
            - name: VNC_NO_PASSWORD
              value: '1'
            - name: SE_NODE_SESSION_TIMEOUT
              value: '600'
            - name: JAVA_OPTS
              value: '-Xmx12288m'
            - name: GRID_TIMEOUT
              value: '6000'
            - name: POOL_MAX
              value: '256'
          resources:
            limits:
              cpu: '20'
              memory: 32Gi
            requests:
              cpu: '10'
              memory: 16Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: dockerhub
      schedulerName: default-scheduler